api:
  address: 0.0.0.0
  port: 3000

bmp:
  address: 0.0.0.0
  port: 4000

kafka:
  address: 10.0.0.100
  port: 9092
  topic: risotto-updates
  batch_max_size: 10

state:
  enable: true
  path: /app/dump.txt
  save_interval: 10