api:
  address: 0.0.0.0
  port: 3000

bmp:
  address: 0.0.0.0
  port: 4000

kafka:
  address: 10.0.0.100
  port: 9092
  topic: bgp-updates
  batch_max_size: 10

state:
  path: /app/dump.txt
  save_interval: 1
  startup_withdraws_time: 20