api:
  address: 0.0.0.0
  port: 3000

bmp:
  address: 0.0.0.0
  port: 4000

kafka:
  enable: true
  brokers: "10.0.0.100:9092"
  auth_protocol: PLAINTEXT
  topic: risotto-updates

state:
  enable: false
  path: /app/state.json
  save_interval: 10