services:
  # GoBGP
  gobgp10:
    image: jauderho/gobgp:latest
    command: gobgpd --config-file /etc/gobgp/gobgp.toml
    platform: linux/amd64
    volumes:
      - ./config/gobgp/gobgp10.toml:/etc/gobgp/gobgp.toml:ro
    networks:
      integration:
        ipv4_address: 10.0.0.10
    depends_on:
      - risotto

  gobgp20:
    image: jauderho/gobgp:latest
    command: gobgpd --config-file /etc/gobgp/gobgp.toml
    platform: linux/amd64
    volumes:
      - ./config/gobgp/gobgp20.toml:/etc/gobgp/gobgp.toml:ro
    networks:
      integration:
        ipv4_address: 10.0.0.20
    depends_on:
      - risotto

  # Bird
  bird30:
    image: ghcr.io/nxthdr/bird:2.16
    volumes:
      - ./config/bird/bird30.conf:/etc/bird/bird.conf:ro
    networks:
      integration:
        ipv4_address: 10.0.0.30
    depends_on:
      - risotto

  bird40:
    image: ghcr.io/nxthdr/bird:2.16
    volumes:
      - ./config/bird/bird40.conf:/etc/bird/bird.conf:ro
    networks:
      integration:
        ipv4_address: 10.0.0.40
    depends_on:
      - risotto

  # Pipeline
  risotto:
    build: ..
    command: -v --kafka-brokers=10.0.0.100:9092 --curation-state-path=/app/state.bin
    ports:
      - "8080:8080"
    networks:
      integration:
        ipv4_address: 10.0.0.99
    depends_on:
      - redpanda

  redpanda:
    image: redpandadata/redpanda:latest
    command: redpanda start --check=false --overprovisioned --smp 1 --memory 500M
    volumes:
      - ./config/redpanda/redpanda.yml:/etc/redpanda/redpanda.yaml:ro
    networks:
      integration:
        ipv4_address: 10.0.0.100

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./config/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ../risotto/schemas:/var/lib/clickhouse/format_schemas
    networks:
      integration:
        ipv4_address: 10.0.0.200
    depends_on:
      - redpanda

networks:
  integration:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
