services:
  gobgp10:
    image: jauderho/gobgp:latest
    command: gobgpd --config-file /etc/gobgp/gobgp.toml
    platform: linux/amd64
    volumes:
      - ./config/gobgp/gobgp10.toml:/etc/gobgp/gobgp.toml:ro
    networks:
      integration:
        ipv4_address: 10.0.0.10
    depends_on:
      - redpanda
      - clickhouse

  gobgp20:
    image: jauderho/gobgp:latest
    command: gobgpd --config-file /etc/gobgp/gobgp.toml
    platform: linux/amd64
    volumes:
      - ./config/gobgp/gobgp20.toml:/etc/gobgp/gobgp.toml:ro
    networks:
      integration:
        ipv4_address: 10.0.0.20
    depends_on:
      - redpanda
      - clickhouse

  redpanda:
    image: redpandadata/redpanda:latest
    command: redpanda start --check=false --overprovisioned --smp 1 --memory 500M
    volumes:
      - ./config/redpanda/redpanda.yml:/etc/redpanda/redpanda.yaml:ro
    networks:
      integration:
        ipv4_address: 10.0.0.100

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    volumes:
      - ./config/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      integration:
        ipv4_address: 10.0.0.200
    depends_on:
      - redpanda

  risotto:
    build: ..
    command: -v --config /config/risotto.yml
    volumes:
      - ./config/risotto/risotto.yml:/config/risotto.yml
    ports:
      - "3000:3000"
    networks:
      integration:
        ipv4_address: 10.0.0.99
    depends_on:
      - redpanda
      - clickhouse

networks:
  integration:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
